### ISSUE TITLE
Главная. Некорректный текст и пропорции элемента

### ISSUE THREAD

**Issue by nilptrr** [DgtlBureau/zarubin_site#59]
Главная. Некорректный текст и пропорции элемента
Открыть https://www.zarubin.co.uk/
Раздел BUSINESS SOLUTIONS AND EXPERTISE

1. Различаются пропорции элемента
2. Цвет текст элемента

Фактический результат:
![1](https://github.com/DgtlBureau/zarubin_site/assets/90075226/a2d4bd54-3ef7-49bb-bbde-2b34c04d421a)

Ожидаемый результат:
![2](https://github.com/DgtlBureau/zarubin_site/assets/90075226/fbc1ccae-91c9-467f-ba12-4eb9a9ee672a)

https://www.figma.com/design/4iPrhPDkPnx0pxrI9S6qoU/%5B%D0%91%D0%A6%D0%A2%5D-Design-Site-NEW-%F0%9F%94%A5?node-id=303-3899&t=2YCVqISLGnyVeId1-4

**Comment by uzarsalan** [comment]
Макет не подразумевает сохранение пропорций этого элемента
