### ISSUE TITLE
Главная. Отсутствует кнопка и некорректные пропорции элемента

### ISSUE THREAD

**Issue by nilptrr** [DgtlBureau/zarubin_site#60]
Главная. Некорректный текст и пропорции элемента
Открыть https://www.zarubin.co.uk/
Раздел BUSINESS SOLUTIONS AND EXPERTISE

Фактический результат:
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/9fd08db1-351e-41d0-82f3-35cb3e73da27)

Ожидаемый результат:
![Screenshot from 2024-06-24 17-27-45](https://github.com/DgtlBureau/zarubin_site/assets/90075226/a48a7136-355e-4887-841d-0d2206844d91)

https://www.figma.com/design/4iPrhPDkPnx0pxrI9S6qoU/%5B%D0%91%D0%A6%D0%A2%5D-Design-Site-NEW-%F0%9F%94%A5?node-id=305-13092&t=2YCVqISLGnyVeId1-4

**Comment by uzarsalan** [comment]
В правках была просьба убрать кнопку
