### ISSUE TITLE
Главная. Контактные данные

### ISSUE THREAD

**Issue by nilptrr** [DgtlBureau/zarubin_site#70]
Реализация
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/5c04bb93-3ee3-4030-8df8-4a40d9160ac7)

Дизайн
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/33d8bfbe-5e5d-4410-830c-8d6d041bc8ec)

**Comment by uzarsalan** [comment]
Какая почта верная?

**Comment by gronzzz** [comment]
vitaliy@zarubin.co.uk
