### ISSUE TITLE
Главная. Футер

### ISSUE THREAD

**Issue by nilptrr** [DgtlBureau/zarubin_site#73]
Футер. Разделы
Реализация:
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/152bb7e6-f86d-450d-87a3-ee0d12a36e0d)

Макет:
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/6a25250a-dfbb-4a60-b7f0-88722020acb0)

---
Контакты
Реализация:
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/67623a2b-7a9a-4641-98b8-e31de4cf1636)

Макет:
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/cf4dafa3-9080-4ad8-bb6c-3226773d1f18)

**Comment by uzarsalan** [comment]
@nilptrr можно описание к багам плз. Непонятно куда именно смотреть
