### ISSUE TITLE
Главная. SOLUTIONS

### ISSUE THREAD

**Issue by nilptrr** [DgtlBureau/zarubin_site#76]
https://www.zarubin.co.uk/solutions

Макет
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/21dbdc19-da2b-483b-b24f-087baa9f409a)

Реализация
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/c11d9848-c48b-4fab-b7cd-064128965ce8)

**Comment by uzarsalan** [comment]
Комментарий плиз. Непонятно куда смотреть

**Comment by gronzzz** [comment]
Тут всё ок
