### ISSUE TITLE
Блог. Шапка

### ISSUE THREAD

**Issue by nilptrr** [DgtlBureau/zarubin_site#78]
https://www.zarubin.co.uk/blog

1. Раздел не подчеркивается как выбранный
2. Различаются шрифты

Реализация  
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/43886ced-0c25-41b5-b593-4b05a25b1dad)

Макет
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/333d9341-9a6f-44b8-b8b6-6c471302f0d2)

**Comment by uzarsalan** [comment]
В блоге и на других страницах шрифт отличается. Так и должно быть?
