### ISSUE TITLE
Блог. Цвет паттерна на фоне

### ISSUE THREAD

**Issue by nilptrr** [DgtlBureau/zarubin_site#80]
Реализация
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/e1ee0290-8411-427a-8ac8-dcc250c4d12c)

Макет
![image](https://github.com/DgtlBureau/zarubin_site/assets/90075226/843a697f-6980-48a6-9088-6442db6acb33)

**Comment by uzarsalan** [comment]
Изображение экспортировано напрямую из фигмы
